stages:
- test
- deploy

services:
- docker

before_script:
  - docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD} ${REGISTRY_LOGIN_SERVER}
  - export TRAVIS_REPO_NAME=${TRAVIS_REPO_SLUG#*/}
  - env > .env

dist: xenial
language: python
python: 3.7
cache:
  directories:
  - $HOME/.cache/pip

jobs:
  include:
  - stage: test
    name: "Lint"
    script:
    - python setup.py flake8
  - name: "Unit tests"
    script:
    - python setup.py test
  - stage: deploy
    name: "Deploy Docker image"
    script:
    - docker build -t runway:latest -f Dockerfile .
    - version=$(docker run --env-file .env -v `echo $PWD`:/root runway:latest bash -c "cd /root && get_version")

    - echo ${version}
    - docker tag runway:latest ${REGISTRY_LOGIN_SERVER}/${TRAVIS_REPO_NAME}:${version}
    - docker push ${REGISTRY_LOGIN_SERVER}/${TRAVIS_REPO_NAME}:${version}
