stages:
- test
- deploy

services:
- docker

dist: xenial
language: python
python: 3.7
cache:
  directories:
  - $HOME/.cache/pip

jobs:
  include:
  - stage: test
    name: "Lint"
    script:
    - python setup.py flake8
  - name: "Unit tests"
    script:
    - python setup.py test
  - stage: deploy
    name: "Deploy Docker image"
    script:
    - export TRAVIS_REPO_NAME=${TRAVIS_REPO_SLUG#*/}
    - env > .env
    - docker login --username $JFROG_USERNAME --password $JFROG_PASSWORD schipholsdh-docker.jfrog.io
    - docker build -t runway:latest -f Dockerfile .
    - version=$(docker run --env-file .env -v `echo $PWD`:/root runway:latest bash -c "cd /root && get_version")

    - docker tag runway:latest schipholsdh-docker.jfrog.io/runway:${version}
    - docker push schipholsdh-docker.jfrog.io/runway:${version}
