steps:
- task: DockerCompose@0
  displayName: Run python linting
  inputs:
    dockerComposeCommand: |
      run --rm python bash -c "pip install -e .[lint] && flake8"
- task: DockerCompose@0
  displayName: Run python tests
  inputs:
    dockerComposeCommand: |
      run --rm python bash -c "pip install -e .[test] && pytest -vv \
                                                         --cov=sdh_deployment \
                                                         --cov-report xml \
                                                         --cov-report html \
                                                         --junitxml /root/testresults.xml \
                                                         tests"

- task: DockerCompose@0
  displayName: Run Docker linting
  inputs:
    dockerComposeCommand: |
      run --rm hadolint bash -c "hadolint Dockerfile_python && hadolint Dockerfile_pyspark"

- task: PublishTestResults@2
  inputs:
    testResultsFiles: $(System.DefaultWorkingDirectory)/testresults.xml

- task: PublishCodeCoverageResults@1
  displayName: 'Publish coverage results'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage.xml
    reportDirectory: $(System.DefaultWorkingDirectory)/htmlcov
    failIfCoverageEmpty: true

- script: docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD} ${REGISTRY_LOGIN_SERVER}
  displayName: Login to registry

- task: DockerCompose@0
  displayName: Deploy to Azure and Databricks
  inputs:
    dockerComposeCommand: |
      run --rm dockerception run_deployment
  env:
    REGISTRY_USERNAME: ${REGISTRY_USERNAME}
    REGISTRY_PASSWORD: ${REGISTRY_PASSWORD}
    GITHUB_TOKEN: ${GITHUB_TOKEN}
