# hadolint ignore=DL3007
FROM fokkodriesprong/docker-pyspark:latest

COPY setup.py /
COPY README.md /
COPY scripts /scripts
COPY runway /runway

RUN pip install requests==2.20.0
RUN python setup.py install
