FROM python:3.7

ADD setup.py /
ADD README.md /
ADD scripts /scripts
ADD sdh_deployment /sdh_deployment

RUN python setup.py install
RUN pip install azure==4.0.0

RUN pip install azure-mgmt-containerservice==4.2.2 kubernetes==7.0.0

RUN apt-get update && apt-get install -y lsb-release apt-transport-https

# Install kubectl
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN touch /etc/apt/sources.list.d/kubernetes.list
RUN echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
RUN apt-get update && apt-get install -y kubectl
