azure:
  resource_group: "sdh{dtap}"
  location: "west europe"
  vault_name: "https://sdhkeyvault{dtap}.vault.azure.net/"
  common:
    shared_registry: sdhcontainerregistryshared.azurecr.io

  keyvault_keys:
    container_registry:
      username: "registry-username"
      password: "registry-password"
      registry: "registry-server"

environment_keys:
  application_name: CI_PROJECT_NAME
  branch_name: CI_COMMIT_REF_SLUG

ci_environment_keys_dev:
  azure_service_principal:
    tenant: "AZURE_TENANTID"
    client_id: "AZURE_KEYVAULT_SP_USERNAME_DEV"
    secret: "AZURE_KEYVAULT_SP_PASSWORD_DEV"

ci_environment_keys_acp:
  azure_service_principal:
    tenant: "AZURE_TENANTID"
    client_id: "AZURE_KEYVAULT_SP_USERNAME_ACP"
    secret: "AZURE_KEYVAULT_SP_PASSWORD_ACP"

ci_environment_keys_prd:
  azure_service_principal:
    tenant: "AZURE_TENANTID"
    client_id: "AZURE_KEYVAULT_SP_USERNAME_PRD"
    secret: "AZURE_KEYVAULT_SP_PASSWORD_PRD"

