azure:
  resource_group_naming: "sdh{env}"
  location: "west europe"
  keyvault_naming: "https://sdhkeyvault{env}.vault.azure.net/"

  keyvault_keys:
    container_registry:
      username: "registry-username"
      password: "registry-password"
      registry: "registry-server"

environment_keys:
  application_name: CIRCLE_PROJECT_REPONAME
  branch_name: CIRCLE_BRANCH

ci_environment_keys_dev:
  azure_service_principal:
    tenant: "AZURE_TENANTID"
    client_id: "AZURE_KEYVAULT_SP_USERNAME_DEV"
    secret: "AZURE_KEYVAULT_SP_PASSWORD_DEV"

ci_environment_keys_acp:
  azure_service_principal:
    tenant: "AZURE_TENANTID"
    client_id: "AZURE_KEYVAULT_SP_USERNAME_ACP"
    secret: "AZURE_KEYVAULT_SP_PASSWORD_ACP"

ci_environment_keys_prd:
  azure_service_principal:
    tenant: "AZURE_TENANTID"
    client_id: "AZURE_KEYVAULT_SP_USERNAME_PRD"
    secret: "AZURE_KEYVAULT_SP_PASSWORD_PRD"
