version: '3.7'

services:

  mockserver:
    container_name: mockserver
    image: jamesdbloom/mockserver:mockserver-5.5.1
    ports:
      - 1080:1080
      - 1081:1081
    environment:
      - LOG_LEVEL=INFO
      - SERVER_PORT="1080,1081"
