azure:
  resource_group_naming: "sdh{env}"
  keyvault_naming: "https://sdhkeyvault{env}.vault.azure.net/"
  location: "west europe"

  keyvault_keys:
    databricks:
      host: "azure-databricks-host"
      token: "azure-databricks-token"

common_environment_keys:
  application_name: CI_PROJECT_NAME
  branch_name: CI_BRANCH_NAME

common:
  databricks_library_path: "dbfs:/libraries"

ci_environment_keys_dev:
  service_principal:
    tenant: "AZURE_TENANTID"
    client_id: "AZURE_KEYVAULT_SP_USERNAME_DEV"
    secret: "AZURE_KEYVAULT_SP_PASSWORD_DEV"

ci_environment_keys_acp:
  service_principal:
    tenant: "AZURE_TENANTID"
    client_id: "AZURE_KEYVAULT_SP_USERNAME_ACP"
    secret: "AZURE_KEYVAULT_SP_PASSWORD_ACP"

ci_environment_keys_prd:
  service_principal:
    tenant: "AZURE_TENANTID"
    client_id: "AZURE_KEYVAULT_SP_USERNAME_PRD"
    secret: "AZURE_KEYVAULT_SP_PASSWORD_PRD"
