#!/usr/bin/python3

import os
from pyspark_streaming_deployment import main
from pyspark_streaming_deployment.create_databricks_secrets import create_secrets

os.chdir('/root')
main.main(create_secrets)
