#!/usr/bin/python3

import os
from pyspark_streaming_deployment import main
from pyspark_streaming_deployment.deploy_to_databricks import deploy_application

os.chdir('/root')
main.main(deploy_application)
