#!/usr/bin/python3
from takeoff.deploy import get_environment
from takeoff.util import load_yaml, get_full_yaml_filename

config = load_yaml(get_full_yaml_filename("config"))
env = get_environment(config)

print(env.artifact_tag)
