#!/usr/bin/python3 -u
import click
from takeoff.deploy import main as takeoff_main


@click.command()
@click.option('--takeoff_dir', default=".takeoff", help='')
def main(takeoff_dir):
    takeoff_main(takeoff_dir)


if __name__ == "__main__":
    main()
